# Generated by Django 2.1.1 on 2018-10-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('entity', models.CharField(max_length=1)),
                ('value', models.FloatField()),
                ('string', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'data',
            },
        ),
    ]
