# Generated by Django 2.1.1 on 2018-10-01 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table=None,
        ),
    ]
