# Generated by Django 2.1.1 on 2018-10-01 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181001_1209'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table='data',
        ),
    ]
